[package]
name = "neqo-common"
version = "0.6.8"
authors = ["Bobby Holley <bobbyholley@gmail.com>"]
edition = "2018"
rust-version = "1.70.0"
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
cfg_aliases = "0.2.0"

[dependencies]
log = { version = "0.4.0", default-features = false }
env_logger = { version = "0.10", default-features = false }
lazy_static = "1.3.0"
qlog = "0.11.0"
time = { version = "=0.3.23", features = ["formatting"] }
nix = { git = "https://github.com/larseggert/nix.git", branch = "feat-tos", features = [
        "socket",
        "net",
        "uio",
], optional = true }
mio = { version = "0.6.17", optional = true }

[features]
deny-warnings = []
ci = []
socket = ["dep:nix", "dep:mio"]

[target."cfg(windows)".dependencies.winapi]
version = "0.3"
features = ["timeapi"]
