name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  MOZBUILD_STATE_PATH: ${{ github.workspace }}\mozbuild
  CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: true

jobs:
  check:
    name: Neqo Build and Test
    strategy:
      # fail-fast: false
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest] #
        rust-toolchain: [stable] # , 1.65.0
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gyp mercurial ninja-build

      - name: Install Dependencies (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew install ninja mercurial
          python3 -m pip install gyp-next
          export PATH="$(python3 -m site --user-base)/bin:$PATH"

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install --no-progress MozillaBuild
          ls -l "C:\ProgramData"
          find "C:\ProgramData\Mozilla-1de4eec8-1241-4177-a864-e594e8d1fb38"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
          cache: false # enabling the cache leads to spurious failures

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo +${{ matrix.rust-toolchain }} build -v --tests

      - name: Run Tests
        run: cargo +${{ matrix.rust-toolchain }} test -v
        env:
           RUST_BACKTRACE: 1
           RUST_LOG: neqo=debug

      - name: Check formatting
        run: cargo +${{ matrix.rust-toolchain }} fmt --all -- --check
        if: ${{ success() || failure() }}

      - name: Clippy
        run: cargo +${{ matrix.rust-toolchain }} clippy -v --tests -- -D warnings
        if: ${{ success() || failure() }}
